function Close = Importfile_LCOBrentCrudeOil(workbookFile,sheetName,startRow,endRow)
%IMPORTFILE Import data from a spreadsheet
%   Open = IMPORTFILE(FILE) reads data from the first worksheet in the
%   Microsoft Excel spreadsheet file named FILE and returns the data as
%   column vectors.
%
%   Open = IMPORTFILE(FILE,SHEET) reads from the specified worksheet.
%
%   Open = IMPORTFILE(FILE,SHEET,STARTROW,ENDROW) reads from the specified
%   worksheet for the specified row interval(s). Specify STARTROW and
%   ENDROW as a pair of scalars or vectors of matching size for
%   dis-contiguous row intervals. To read to the end of the file specify an
%   ENDROW of inf.%
% Example:
%   Open = importfile('Data_LCO_BrentCrudeOil.xlsx','brent_1D',2,1918);
%
%   See also XLSREAD.

% Auto-generated by MATLAB on 2014/06/16 18:06:58

%% Input handling

% If no sheet is specified, read first sheet
if nargin == 1 || isempty(sheetName)
    sheetName = 1;
end

% If row start and end points are not specified, define defaults
if nargin <= 3
    startRow = 2;
    endRow = 1918;
end

%% Import the data
data = xlsread(workbookFile, sheetName, sprintf('D%d:D%d',startRow(1),endRow(1)));
for block=2:length(startRow)
    tmpDataBlock = xlsread(workbookFile, sheetName, sprintf('C%d:C%d',startRow(block),endRow(block)));
    data = [data;tmpDataBlock]; %#ok<AGROW>
end

%% Allocate imported array to column variable names
Close = data(:,1);

