function createPlot(Dates, LongClose, ShortClose,Close)
%CREATEFIGURE1(X1, Y1, X2, Y2, X3, Y3)
%  X1:  vector of x data
%  Y1:  vector of y data
%  X2:  vector of x data
%  Y2:  vector of y data
%  X3:  vector of x data
%  Y3:  vector of y data

%  Auto-generated by MATLAB on 26-Apr-2017 14:38:47

% Create figure
figure1 = figure('Color',[1 1 1]);

% Create subplot
subplot1 = subplot(2,1,1,'Parent',figure1);
hold(subplot1,'on');

% Create plot
plot(Dates,LongClose,'Parent',subplot1,'Marker','o','LineStyle','none',...
    'Color',[0 1 0]);

% Create plot
plot(Dates,ShortClose,'Parent',subplot1,'Marker','+','LineStyle','none',...
    'Color',[1 0 0]);

% Create plot
plot(Dates,Close,'Parent',subplot1,'Color',[0 0 0]);

% Create title
title('Short/Long Graph');

box(subplot1,'on');
% Set the remaining axes properties
set(subplot1,'XGrid','on','YGrid','on');
% Create axes
axes1 = axes('Parent',figure1,...
    'Position',[0.13 0.11 0.775 0.341162790697674]);
hold(axes1,'on');

% Create plot
plot(Dates,Close,'Parent',axes1,'DisplayName','Close vs Date');

% Create title
title('Close Price');

box(axes1,'on');
% Set the remaining axes properties
set(axes1,'XGrid','on','YGrid','on');
