function createfigure1(Dates, Close, Date1, Returns)
%CREATEFIGURE1(X1, Y1, DATE1, RETURNS1)
%  X1:  vector of x data
%  Y1:  vector of y data
%  DATE1:  vector of x data
%  RETURNS1:  vector of y data

%  Auto-generated by MATLAB on 26-Apr-2017 14:44:15

% Create figure
figure1 = figure;

% Create subplot
subplot1 = subplot(2,1,1,'Parent',figure1);
hold(subplot1,'on');

% Create plot
plot(Dates,Close,'Parent',subplot1,'MarkerSize',1,'Marker','diamond',...
    'LineWidth',2,...
    'LineStyle','--',...
    'Color',[0.749019622802734 0 0.749019622802734]);

box(subplot1,'on');
% Set the remaining axes properties
set(subplot1,'Color',[1 0.968627452850342 0.921568632125854],'XGrid','on',...
    'YGrid','on');
% Create axes
axes1 = axes('Parent',figure1,...
    'Position',[0.13 0.11 0.775 0.341162790697674]);
hold(axes1,'on');

% Create plot
plot(Date1,Returns,'Parent',axes1,'DisplayName','returns vs Date(2:end)');

box(axes1,'on');
% Set the remaining axes properties
set(axes1,'XGrid','on','YGrid','on');
