function createSimplePlot(Y1, YMatrix1)
%CREATEFIGURE1(Y1, YMATRIX1)
%  Y1:  vector of y data
%  YMATRIX1:  matrix of y data

%  Auto-generated by MATLAB on 23-Feb-2017 09:03:25

% Create figure
figure1 = figure('Color',...
    [0.800000011920929 0.800000011920929 0.800000011920929]);

% Create subplot
subplot1 = subplot(2,1,1,'Parent',figure1);
hold(subplot1,'on');

% Create plot
plot(Y1,'Parent',subplot1,'MarkerFaceColor',[1 0 0],'MarkerSize',3,...
    'Marker','diamond',...
    'LineWidth',1);

% Create title
title('Evolutionary Learning Results, Sharpe Ratio = 2.28',...
    'FontName','Iskoola Pota');

% Create ylabel
ylabel('Price (USD)');

% Uncomment the following line to preserve the X-limits of the axes
% xlim(subplot1,[1 868]);
box(subplot1,'on');
% Set the remaining axes properties
set(subplot1,'Color',[1 0.968627452850342 0.921568632125854]);
% Create subplot
subplot2 = subplot(2,1,2,'Parent',figure1);
hold(subplot2,'on');

% Create multiple lines using matrix input to plot
plot1 = plot(YMatrix1,'Parent',subplot2);
set(plot1(1),'DisplayName','Position');
set(plot1(2),'DisplayName','Cumulative Return');

% Create xlabel
xlabel('Serial time number');

% Create title
title('Final Return = 24.6 (113%)');

% Create ylabel
ylabel('Price (USD)');

box(subplot2,'on');
axis(subplot2,'tight');
% Create legend
legend1 = legend(subplot2,'show');
set(legend1,'Location','best');

