function createfigure(Dates, Prices, Returns)
%CREATEFIGURE(X1, Y1, DATA1)
%  X1:  vector of x data
%  Y1:  vector of y data
%  DATA1:  histogram data

%  Auto-generated by MATLAB on 10-Feb-2016 00:44:08

% Create figure
figure1 = figure;

% Create subplot
subplot1 = subplot(2,1,1,'Parent',figure1);
hold(subplot1,'on');

% Create datetime plot
plot(Dates,Prices,'Parent',subplot1);

% Create title
title('Time Series');

%% Uncomment the following line to preserve the Y-limits of the axes
% ylim(subplot1,[20 160]);
box(subplot1,'on');
% Set the remaining axes properties
set(subplot1,'Color',[1 0.968627452850342 0.921568632125854],'XGrid','on',...
    'YGrid','on');
% Create subplot
subplot2 = subplot(2,1,2,'Parent',figure1);

% Create histogram
histogram(Returns,'DisplayName','Returns','Parent',subplot2,...
    'BinMethod','auto');

% Create title
title('Return Histogram');

%% Uncomment the following line to preserve the X-limits of the axes
% xlim(subplot2,[-0.15 0.3]);
box(subplot2,'on');
