function [Date,Volume,Open,Close,High,Low] = importPriceData(workbookFile,sheetName,startRow,endRow)
%IMPORTFILE2 Import data from a spreadsheet
%   [Date,Volume,Open,Close,High,Low] = IMPORTFILE2(FILE) reads data from
%   the first worksheet in the Microsoft Excel spreadsheet file named FILE
%   and returns the data as column vectors.
%
%   [Date,Volume,Open,Close,High,Low] = IMPORTFILE2(FILE,SHEET) reads from
%   the specified worksheet.
%
%   [Date,Volume,Open,Close,High,Low] =
%   IMPORTFILE2(FILE,SHEET,STARTROW,ENDROW) reads from the specified
%   worksheet for the specified row interval(s). Specify STARTROW and
%   ENDROW as a pair of scalars or vectors of matching size for
%   dis-contiguous row intervals. To read to the end of the file specify an
%   ENDROW of inf.%
% Example:
%   [Date,Volume,Open,Close,High,Low] = importfile2('Data_LCO_BrentCrudeOil.xlsx','brent_1D',2,1918);
%
%   See also XLSREAD.

% Auto-generated by MATLAB on 2017/04/26 14:20:33

%% Input handling

% If no sheet is specified, read first sheet
if nargin == 1 || isempty(sheetName)
    sheetName = 1;
end

% If row start and end points are not specified, define defaults
if nargin <= 3
    startRow = 2;
    endRow = 1918;
end

%% Import the data, extracting spreadsheet dates in Excel serial date format
[~, ~, raw, dates] = xlsread(workbookFile, sheetName, sprintf('A%d:F%d',startRow(1),endRow(1)),'' , @convertSpreadsheetExcelDates);
for block=2:length(startRow)
    [~, ~, tmpRawBlock,tmpDateNumBlock] = xlsread(workbookFile, sheetName, sprintf('A%d:F%d',startRow(block),endRow(block)),'' , @convertSpreadsheetExcelDates);
    raw = [raw;tmpRawBlock]; %#ok<AGROW>
    dates = [dates;tmpDateNumBlock]; %#ok<AGROW>
end
raw = raw(:,[2,3,4,5,6]);
dates = dates(:,1);

%% Create output variable
I = cellfun(@(x) ischar(x), raw);
raw(I) = {NaN};
data = reshape([raw{:}],size(raw));

%% Allocate imported array to column variable names
dates(~cellfun(@(x) isnumeric(x) || islogical(x), dates)) = {NaN};
Date = datetime([dates{:,1}].', 'ConvertFrom', 'Excel');
Volume = data(:,1);
Open = data(:,2);
Close = data(:,3);
High = data(:,4);
Low = data(:,5);

% For code requiring serial dates (datenum) instead of datetime, uncomment
% the following line(s) below to return the imported dates as datenum(s).

% Date=datenum(Date);

