function ruleChartMA(YMatrix1, YMatrix2, sh)
%CREATEFIGURE(YMATRIX1,YMATRIX2)
%  YMATRIX1:  matrix of y data
%  YMATRIX2:  matrix of y data

%  Auto-generated by MATLAB on 08-Mar-2011 10:55:35
%  Small customizations also performed to make a dynamic title and linked
%  axes.

% Create figure
figure1 = figure;

% Create subplot
subplot1 = subplot(4,1,1,'Parent',figure1,'YGrid','on','XGrid','on');
box(subplot1,'on');
hold(subplot1,'all');

% Create multiple lines using matrix input to plot
plot1 = plot(YMatrix1,'Parent',subplot1);
set(plot1(1),'DisplayName','Close');
set(plot1(2),'DisplayName','Lead');
set(plot1(3),'DisplayName','Lag');

% Create title
title(['First pass results: Annual Sharpe ratio = ', num2str(sh,3)]);

% 
subplot2 = subplot(4,1,2,'Parent',figure1,'YGrid','on','XGrid','on');
x = 1:size(YMatrix2,1);
Signal = YMatrix2(:,1);
Signal_Buy = zeros(size(Signal));
Signal_Sell = zeros(size(Signal));
Signal_Buy(Signal > 0) = Signal(Signal > 0);
Signal_Sell(Signal < 0) = Signal(Signal < 0);
bar(subplot2,x,Signal_Buy,'Green')
subplot3 = subplot(4,1,3,'Parent',figure1,'YGrid','on','XGrid','on');
bar(subplot3,x,Signal_Sell,'Red')


% Create subplot
subplot4 = subplot(4,1,4,'Parent',figure1,'YGrid','on','XGrid','on');
box(subplot4,'on');
hold(subplot4,'all');
plot2 = plot(YMatrix2(:,2),'Parent',subplot4);
set(plot2,'DisplayName','Cumulative return');

% Create legend
legend1 = legend(subplot4,'show');
set(legend1,'Location','Best');

% Create xlabels
xlabel(subplot1, 'Serial day number');
xlabel(subplot2, 'Serial day number');
xlabel(subplot3, 'Serial day number');
xlabel(subplot4, 'Serial day number');

% Create ylabels
ylabel(subplot1, '\bf Price ($)');
ylabel(subplot2, '\bf Buy');
ylabel(subplot3, '\bf Sell');
ylabel(subplot4, '\bf Returns ($)');

% Title
title(subplot1, '\bf Lead-Lag Price Chart');
title(subplot2, '\bf Buy Signal');
title(subplot3, '\bf Sell Signal');
title(subplot4, '\bf Returns ($)');

% Link Axes
linkaxes([subplot1, subplot2, subplot3, subplot4],'x')
